[package]
name = "game_ex"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[dependencies.sdl2]
version = "0.38.0"
default-features = false
features = ["ttf","gfx","image"] 
